### ISSUE TITLE
Update readme instructions to match ROS 2.0

### ISSUE THREAD

**Issue by bmunkholm** [realm-demos/realm-crowdcircle#4]
The instructions below are no longer correct. There is another default user and starting the server and Studio is different.

3. Start Realm Object Server on a local Mac.
4. Create a user in the RMP Dashboard, enter 'crowdcircle@realm.io' and 'password' respectively as username and password.

**Comment by dhmspector** [comment]
1) There is no other default user for crowd circle - `crowdcircle@realm.io` Is the default user as per the constants file. 
2) Other issues fixed by https://github.com/realm-demos/realm-crowdcircle/commit/14aec25487766a237cd0fc7b1be41c3b16c3a67d
